server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/torrefactora
    username: torrefactora
    password: torrefactora
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL8Dialect